encoding: utf-8

# SEOç›¸å…³ä¿¡æ¯
title: å’•å’šåŒå­¦
description: ç‹¬ç«‹å¼€å‘è€…ï¼ŒinBox ç¬”è®°ä½œè€…
keywords: å’•å’š,Blog,Java,Html,JavaScript,PicPlus,å’•å’šäº‘å›¾
author: å’•å’š
footerText: 'Copyright Â© 2022 å’•å’š'
footerIcp: 'é™‡ICPå¤‡2022001147å·'

# è¿™äº›ä¸è¦åŠ¨
permalink: /:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# åŸŸåé…ç½®
# baseurlé…ç½®,å¦‚æœç½‘ç«™éƒ¨ç½²åœ¨æ ¹ç›®å½•ä¸‹çš„å…¶ä»–ç›®å½•ä¸­ï¼Œè¯·è®¾ç½®ä¸º /ç›®å½•å
domainUrl: 'https://gudong.site'
baseurl: ''

# åä¸ªæ§½åœ°å€ï¼Œä¼šåœ¨chaté¡µé¢ä¸­é‡å®šå‘åˆ°è¯¥åœ°å€
tucaoUrl: https://weibo.com/u/1874136301

# èœå•
menu:
  - title: é¦–é¡µ
    url: /
  # - title: å’šè®°
  #   url: /daily.html
  # - title: å½’ç±»
  #   url: /categories.html
  - title: ä½œå“
    url: /works.html
  # - title: æœç´¢
  #   url: /search.html
  - title: å‹é“¾
    url: links.html
  # - title: ç•™è¨€
  #   url: /chat.html
  - title: è®¢é˜…
    url: /subscribe.html
  - title: å…³äº
    url: /about.html

# ç‚¹å‡»é¡µé¢æ–‡å­—å†’å‡ºç‰¹æ•ˆ,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extClickEffect: false

# Google Adsense,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
# _includes/ext-adsense.html é‡Œé¢ä¿®æ”¹ä¸ºè‡ªå·±çš„é…ç½®
extAdsense: false

# è…¾è®¯MTAç§»åŠ¨åˆ†æ,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
# _includes/ext-adsense.html é‡Œé¢ä¿®æ”¹ä¸ºè‡ªå·±çš„é…ç½®
extMTA: false

# ç™¾åº¦æ”¶å½•è‡ªåŠ¨æ¨é€,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extBaidu: true

# æ•°å­¦å…¬å¼æ”¯æŒï¼Œæ¯”è¾ƒå½±å“åŠ è½½é€Ÿåº¦,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extMath: false

# æ˜¯å¦æ”¯æŒè¯„è®º
enableComment: true

rssCount: 15

profile_icon: /assets/profile/gudong_2023.png

# åº”ç”¨å›¾æ ‡
app_icons:
  inbox: /assets/app_icon/ic_launcher_inbox.png
  cang: /assets/app_icon/ic_launcher_cang.jpg
  light: /assets/app_icon/ic_launcher_light.png
  rssplus: /assets/app_icon/ic_launcher_rss.png
  picplus: /assets/app_icon/ic_launcher_pic.png

# å‹æƒ…é“¾æ¥
links:
  - title: TMaize
    url: https://blog.tmaize.net/
    desc: TMaizeçš„ä¸ªäººåšå®¢
    tag:  å‰ç«¯ æ•°æ®åº“ åç«¯ Java NodeJS GO
    header: https://blog.tmaize.net/static/img/logo.jpg

  - title: å…ƒè§†è§’
    url: https://blog.yuanpei.me
    desc: èµ·é£äº†ï¼Œå”¯æœ‰åŠªåŠ›ç”Ÿå­˜
    tag: æ•°æ®åˆ†æ å¾®æœåŠ¡ Web
    header: https://blog.yuanpei.me/img/default-avatar_hua3ac297279c484e6ad1f3f5acd3cb005_125342_300x0_resize_q75_box.jpg

  - title: Jason
    url: https://atjason.com/
    desc: Jasonï¼Œç‹¬ç«‹å¼€å‘è€…ï¼Œè‡ªç”±èŒä¸šè€…
    tag: é‡åŒ–æŠ•èµ„ Macå¼€å‘è€…
    header: https://ps.toolinbox.net/ezw8l.jpg

  - title: èƒ¡æ¶‚è¯´
    url: https://hutusi.com/
    desc: ä»»æŠ›æ˜Ÿæ±‰å½’å›­åœƒï¼Œç•™å–ä¹¾å¤ç››é…’å›Š
    tag: åšä¸»
    header: https://hutusi.com/assets/apple-touch-icon.png

  - title: åœŸæœ¨å›å­
    url: https://tumutanzi.com/
    desc: å’Œå…‰åŒå°˜ï¼Œä¸æ—¶èˆ’å·
    tag: åšä¸»
    header: https://cravatar.cn/avatar/a4368b0f22f9820265d7d2431addc8da?s=120&r=g

  - title: YuZhangWang
    url: https://www.yuzhang.wang/
    desc: PLUSULTRAï¼ 
    tag: åšä¸»
    header: https://gcore.jsdelivr.net/gh/YuZhangWang/Creative-pictures02@master/img/202210171416164.png

  - title: å¾€æ—¥ä¿¡ç¬º
    url: https://www.xingmail.cn/
    desc: ä¸€ä¸ªXingåˆ†äº«è‡ªå·±çš„æ•…äº‹çš„åœ°æ–¹
    tag: åšä¸» æ•…äº‹
    header: https://www.xingmail.cn/favicon.webp

  - title: å…³å…³å’Œå…­å…­
    url: https://www.gmcllp.cn
    desc: å‘ä¸–ç•Œåˆ†äº«æˆ‘ä»¬çš„æ•…äº‹
    tag: åšä¸» æ•…äº‹ ç”Ÿæ´»
    header: https://www.gmcllp.cn/logo-y.png

  - title: åšå®¢æ˜Ÿçƒ
    url: https://www.blogplanet.cn/
    desc: æ¯ä¸€ä¸ªåšå®¢éƒ½æ˜¯ä¸€ä¸ªç‹¬ç«‹æ˜Ÿçƒï¼
    tag: åšå®¢ ç¤¾åŒº
    header: https://www.blogplanet.cn/img/bkxq.png

  - title: é˜¿é”‹çš„å°å®‡å®™
    url: https://feng.pub
    desc: æ²§æµ·ä¸€ç²Ÿï¼Œå¾®äº®è€Œæ¸ºå°ã€‚
    tag: åšä¸» éšç¬”
    header: https://cravatar.cn/avatar/868740183b995d2707e307ce0a89633a?s=200

  - title: Mark's Blog
    url: https://mark.vergilisme.com/
    desc: è®°å½•ç”Ÿæ´»ï¼Œåˆ†äº«æ‰€æ€
    tag: åšä¸» æŠ€æœ¯
    header: https://mark.vergilisme.com/favicon.ico

  - title: å—å·åŸæ¢¦
    url: https://blog.southz.top/
    desc: äººç”Ÿèƒ½æœ‰å‡ å›æï¼Œå¤©æ¶¯ä½•å¤„æ— èŠ³è‰ğŸŒŸ
    tag: åšä¸» æŠ€æœ¯
    header: https://cn.cravatar.com/avatar/8418eeff381919776ab9bdb0bf488d5a?s=96&d=mp&r=g

  - title: é™¶å…¶çš„ä¸ªäººåšå®¢
    url: https://www.tqazy.com
    desc: å½“ä¸‹ï¼Œå³æ˜¯æœªæ¥
    tag: åšä¸» æŠ€æœ¯
    header: https://oss.tqazy.com/wordpress/resources/img/taoqilogo.jpg

  - title: äºŒåå…­
    url: https://www.ershiliu.com/
    desc: äººç”Ÿå¦‚é€†æ—…ï¼Œæˆ‘äº¦æ˜¯è¡Œäººã€‚
    tag: åšä¸» éšç¬”
    header: https://www.ershiliu.com/tx.jpeg


