encoding: utf-8

# SEO相关信息
title: 咕咚同学
description: 一个独立开发者的日常
keywords: 咕咚,Blog,Java,Html,JavaScript,PicPlus,咕咚云图
author: 咕咚
footerText: 'Copyright © 2022 咕咚'
footerIcp: '陇ICP备2022001147号'

# 这些不要动
permalink: /:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://gudong.site'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://weibo.com/u/1874136301

# 菜单
menu:
  - title: 首页
    url: /
  # - title: 咚记
  #   url: /daily.html
  # - title: 归类
  #   url: /categories.html
  - title: 作品
    url: /works.html
  # - title: 搜索
  #   url: /search.html
  - title: 友链
    url: /links.html
  # - title: 留言
  #   url: /chat.html
  - title: 订阅
    url: /subscribe.html
  - title: 关于
    url: /about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 腾讯MTA移动分析,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extMTA: false

# 百度收录自动推送,不需要请设置为false
extBaidu: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 是否支持评论
enableComment: true

rssCount: 15

profile_icon: /assets/profile/gudong_2023.png

# 应用图标
app_icons:
  inbox: /assets/app_icon/ic_launcher_inbox.png
  cang: /assets/app_icon/ic_launcher_cang.jpg
  light: /assets/app_icon/ic_launcher_light.png
  rssplus: /assets/app_icon/ic_launcher_rss.png
  picplus: /assets/app_icon/ic_launcher_pic.png

# 友情链接
links:
  - title: TMaize
    url: https://blog.tmaize.net/
    desc: TMaize的个人博客
    tag:  前端 数据库 后端 Java NodeJS GO
    header: https://blog.tmaize.net/static/img/logo.jpg

  - title: 元视角
    url: https://blog.yuanpei.me
    desc: 起风了，唯有努力生存
    tag: 数据分析 微服务 Web
    header: https://blog.yuanpei.me/img/default-avatar_hua3ac297279c484e6ad1f3f5acd3cb005_125342_300x0_resize_q75_box.jpg

  - title: Jason
    url: https://atjason.com/
    desc: Jason，独立开发者，自由职业者
    tag: 量化投资 Mac开发者
    header: https://ps.toolinbox.net/ezw8l.jpg

  - title: 胡涂说
    url: https://hutusi.com/
    desc: 任抛星汉归园圃，留取乾坤盛酒囊
    tag: 博主
    header: https://hutusi.com/assets/apple-touch-icon.png

  - title: 土木坛子
    url: https://tumutanzi.com/
    desc: 和光同尘，与时舒卷
    tag: 博主
    header: https://cravatar.cn/avatar/a4368b0f22f9820265d7d2431addc8da?s=120&r=g

  - title: YuZhangWang
    url: https://www.yuzhang.wang/
    desc: PLUSULTRA！ 
    tag: 博主
    header: https://gcore.jsdelivr.net/gh/YuZhangWang/Creative-pictures02@master/img/202210171416164.png

  - title: 往日信笺
    url: https://www.xingmail.cn/
    desc: 一个Xing分享自己的故事的地方
    tag: 博主 故事
    header: https://www.xingmail.cn/favicon.webp

  - title: 关关和六六
    url: https://www.gmcllp.cn
    desc: 向世界分享我们的故事
    tag: 博主 故事 生活
    header: https://www.gmcllp.cn/logo-y.png

  - title: 博客星球
    url: https://www.blogplanet.cn/
    desc: 每一个博客都是一个独立星球！
    tag: 博客 社区
    header: https://www.blogplanet.cn/img/bkxq.png

  - title: 阿锋的小宇宙
    url: https://feng.pub
    desc: 沧海一粟，微亮而渺小。
    tag: 博主 随笔
    header: https://cravatar.cn/avatar/868740183b995d2707e307ce0a89633a?s=200

  - title: Mark's Blog
    url: https://mark.vergilisme.com/
    desc: 记录生活，分享所思
    tag: 博主 技术
    header: https://mark.vergilisme.com/favicon.ico

  - title: 南川吟梦
    url: https://blog.southz.top/
    desc: 城南花已开，愿君常安在
    tag: 博主 技术
    header: https://cn.cravatar.com/avatar/8418eeff381919776ab9bdb0bf488d5a?s=96&d=mp&r=g

  - title: 陶其的个人博客
    url: https://www.tqazy.com
    desc: 当下，即是未来
    tag: 博主 技术
    header: https://oss.tqazy.com/wordpress/resources/img/taoqilogo.jpg

  - title: 二十六
    url: https://www.ershiliu.com/
    desc: 人生如逆旅，我亦是行人。
    tag: 博主 随笔
    header: https://www.ershiliu.com/tx.jpeg

  - title: 洗子の小窝
    url: https://xizi.live/
    desc: 但行己路 无问山海
    tag: 博主 随笔
    header: https://cozier-1315026820.cos.ap-guangzhou.myqcloud.com/%E5%A4%B4%E5%83%8F1.png

  - title: 林海草原
    url: https://gravatar.loli.net/
    desc: 愿我经历的苦难你不要经历，愿我已有的幸福你触手可及
    tag: 博主 随笔 生活
    header: https://gravatar.loli.net/avatar/8391fb097fff7eec5ff0a8877b94967b

  - title: forecho's Blog
    url: https://blog.forecho.com
    desc: 把生命浪费在美好的事物上
    tag: 博主 技术 投资
    header: https://gravatar.loli.net/avatar/c7c95fe80293c0a114a2c3b0daa24003?s=150

  - title: 蘇 SU
    url: https://suus.me/
    desc: A nook where thoughts and ideas sometimes echo
    tag: 博主 随笔 技术
    header: https://cravatar.cn/avatar/4924b5f45b6b65e4925c35f9056fe3e7?s=80

  - title: 朱某的生活印记
    url: https://zhuxu.asia/
    desc: 没有销声匿迹，我在热爱生活
    tag: 博主 生活 随笔
    header: https://img1.zhuxu.asia/img/logo500.png

  - title: 墨迹日志
    url: https://log.ink/
    desc: 虽多尘色染，犹见墨痕浓
    tag: 博主 随笔 生活
    header: https://log.ink/wp-content/uploads/2024/12/cropped-%E5%A4%B4%E5%83%8F.png

  - title: 杜老师说
    url: https://dusays.com/
    desc: 师者，传道，授业，解惑！
    tag: 技术 运维 资源分享 教程
    header: https://dusays.com/avatar.png

  - title: 喵喵の小窝
    url: https://blog.meowo.moe/
    desc: フランドール・スカーレット赛高！
    tag: 博主 ACG 生活
    header: https://server.meowo.moe/api/v2/objects/avatar/o4cctz9mtnt6hmz0yv.jpg

  - title: XiaoPang的个人博客
    url: https://blog.xpdbk.com
    desc: 追随梦想需竭尽全力
    tag: 博主 技术 生活
    header: https://img.xpdbk.com/file/imglol/img/avatar.jpg

  - title: Ximi's Diary
    url: https://www.ximi.me/
    desc: 希米的小窝
    tag: 博主 生活 随笔
    header: https://www.ximi.me/tx.webp

  - title: 刘郎阁
    url: https://vjo.cc/
    desc: 一个积极向上的生活探索者！
    tag: 博主 生活 随笔
    header: https://vjo.cc/usr/uploads/logo.jpeg

  - title: 君主阁
    url: https://gfjzz.cn
    desc: 君主，永远在高峰等你！
    tag: 博主 技术 生活
    header: https://gfjzz.cn/upload/sitelogo.png

  - title: HIPVOGUE
    url: https://hipvogue.com/
    desc: 生活中的每个小事、思考、灵感都值得被记录。
    tag: 博主 生活 随笔
    header: https://hipvogue.com/hipvogue.jpg

  - title: 益友网站
    url: https://www.yiyou.bj.cn
    desc: 美好的日常生活值得我们去记录，希望我们的生活每天都能充满着乐趣跟开心事。
    tag: 博主 生活 随笔
    header: https://www.yiyou.bj.cn/logo/youlogo.png

  - title: RhoPaperの小站
    url: https://rhopaper.top/
    desc: 纸至执
    tag: 博主 随笔
    header: https://rhopaper.top/avatar.jpg

  - title: 小林的小窝
    url: https://www.xiaorin.com
    desc: 分享技术教程、日常
    tag: 博主 技术 生活
    header: https://www.xiaorin.com/Image.jpg

  - title: Jeffer.Z
    url: https://www.jeffer.xyz/
    desc: Welcome to my blog. I am an independent blogger who writes about daily life and WordPress plugins.
    tag: 博主 生活 WordPress插件 随笔
    header: https://www.jeffer.xyz/wp-content/uploads/2023/01/cropped-2023010402181112-250x250.jpg

  - title: 甜小萌
    url: http://www.sweetsmoe.com/
    desc: 甜甜哒~萌萌哒~ε๑⍥๑з
    tag: 博主 生活 萌系
    header: https://www.sweetsmoe.com/upload/linkicon/66b0740dc4ed9aa9435042ac.webp?v=1722840125148

  - title: liuzhen932 的小窝
    url: https://blog.liuzhen932.top/
    desc: 只要愿意去做，人无所不通
    tag: 技术 网络 生活
    header: https://blog.liuzhen932.top/favicon.png

  - title: 熊猫の小窝
    url: https://www.pysio.online/
    desc: 一个温暖的家/一只懒懒的熊猫
    tag: 博主 生活 随笔
    header: https://cdn.akaere.online/https://avatars.githubusercontent.com/u/71202163

  - title: 冬烟 の 小窝
    url: https://blog.45m.fun/
    desc: 你猜，我猜你肯定猜不到嘿嘿……
    tag: 博主 生活 随笔
    header: https://q.qlogo.cn/g?b=qq&nk=3010013479&s=640


