encoding: utf-8

# SEOç›¸å…³ä¿¡æ¯
title: å’•å’šåŒå­¦
description: ä¸€ä¸ªç‹¬ç«‹å¼€å‘è€…çš„æ—¥å¸¸
keywords: å’•å’š,Blog,Java,Html,JavaScript,PicPlus,å’•å’šäº‘å›¾
author: å’•å’š
footerText: 'Copyright Â© 2022 å’•å’š'
footerIcp: 'é™‡ICPå¤‡2022001147å·'

# è¿™äº›ä¸è¦åŠ¨
permalink: /:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# åŸŸåé…ç½®
# baseurlé…ç½®,å¦‚æœç½‘ç«™éƒ¨ç½²åœ¨æ ¹ç›®å½•ä¸‹çš„å…¶ä»–ç›®å½•ä¸­ï¼Œè¯·è®¾ç½®ä¸º /ç›®å½•å
domainUrl: 'https://gudong.site'
baseurl: ''

# åä¸ªæ§½åœ°å€ï¼Œä¼šåœ¨chaté¡µé¢ä¸­é‡å®šå‘åˆ°è¯¥åœ°å€
tucaoUrl: https://weibo.com/u/1874136301

# èœå•
menu:
  - title: é¦–é¡µ
    url: /
  # - title: å’šè®°
  #   url: /daily.html
  # - title: å½’ç±»
  #   url: /categories.html
  - title: ä½œå“
    url: /works.html
  # - title: æœç´¢
  #   url: /search.html
  - title: å‹é“¾
    url: links.html
  # - title: ç•™è¨€
  #   url: /chat.html
  - title: è®¢é˜…
    url: /subscribe.html
  - title: å…³äº
    url: /about.html

# ç‚¹å‡»é¡µé¢æ–‡å­—å†’å‡ºç‰¹æ•ˆ,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extClickEffect: false

# Google Adsense,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
# _includes/ext-adsense.html é‡Œé¢ä¿®æ”¹ä¸ºè‡ªå·±çš„é…ç½®
extAdsense: false

# è…¾è®¯MTAç§»åŠ¨åˆ†æ,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
# _includes/ext-adsense.html é‡Œé¢ä¿®æ”¹ä¸ºè‡ªå·±çš„é…ç½®
extMTA: false

# ç™¾åº¦æ”¶å½•è‡ªåŠ¨æ¨é€,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extBaidu: true

# æ•°å­¦å…¬å¼æ”¯æŒï¼Œæ¯”è¾ƒå½±å“åŠ è½½é€Ÿåº¦,ä¸éœ€è¦è¯·è®¾ç½®ä¸ºfalse
extMath: false

# æ˜¯å¦æ”¯æŒè¯„è®º
enableComment: true

rssCount: 15

profile_icon: /assets/profile/gudong_2023.png

# åº”ç”¨å›¾æ ‡
app_icons:
  inbox: /assets/app_icon/ic_launcher_inbox.png
  cang: /assets/app_icon/ic_launcher_cang.jpg
  light: /assets/app_icon/ic_launcher_light.png
  rssplus: /assets/app_icon/ic_launcher_rss.png
  picplus: /assets/app_icon/ic_launcher_pic.png

# å‹æƒ…é“¾æ¥
links:
  - title: TMaize
    url: https://blog.tmaize.net/
    desc: TMaizeçš„ä¸ªäººåšå®¢
    tag:  å‰ç«¯ æ•°æ®åº“ åç«¯ Java NodeJS GO
    header: https://blog.tmaize.net/static/img/logo.jpg

  - title: å…ƒè§†è§’
    url: https://blog.yuanpei.me
    desc: èµ·é£äº†ï¼Œå”¯æœ‰åŠªåŠ›ç”Ÿå­˜
    tag: æ•°æ®åˆ†æ å¾®æœåŠ¡ Web
    header: https://blog.yuanpei.me/img/default-avatar_hua3ac297279c484e6ad1f3f5acd3cb005_125342_300x0_resize_q75_box.jpg

  - title: Jason
    url: https://atjason.com/
    desc: Jasonï¼Œç‹¬ç«‹å¼€å‘è€…ï¼Œè‡ªç”±èŒä¸šè€…
    tag: é‡åŒ–æŠ•èµ„ Macå¼€å‘è€…
    header: https://ps.toolinbox.net/ezw8l.jpg

  - title: èƒ¡æ¶‚è¯´
    url: https://hutusi.com/
    desc: ä»»æŠ›æ˜Ÿæ±‰å½’å›­åœƒï¼Œç•™å–ä¹¾å¤ç››é…’å›Š
    tag: åšä¸»
    header: https://hutusi.com/assets/apple-touch-icon.png

  - title: åœŸæœ¨å›å­
    url: https://tumutanzi.com/
    desc: å’Œå…‰åŒå°˜ï¼Œä¸æ—¶èˆ’å·
    tag: åšä¸»
    header: https://cravatar.cn/avatar/a4368b0f22f9820265d7d2431addc8da?s=120&r=g

  - title: YuZhangWang
    url: https://www.yuzhang.wang/
    desc: PLUSULTRAï¼ 
    tag: åšä¸»
    header: https://gcore.jsdelivr.net/gh/YuZhangWang/Creative-pictures02@master/img/202210171416164.png

  - title: å¾€æ—¥ä¿¡ç¬º
    url: https://www.xingmail.cn/
    desc: ä¸€ä¸ªXingåˆ†äº«è‡ªå·±çš„æ•…äº‹çš„åœ°æ–¹
    tag: åšä¸» æ•…äº‹
    header: https://www.xingmail.cn/favicon.webp

  - title: å…³å…³å’Œå…­å…­
    url: https://www.gmcllp.cn
    desc: å‘ä¸–ç•Œåˆ†äº«æˆ‘ä»¬çš„æ•…äº‹
    tag: åšä¸» æ•…äº‹ ç”Ÿæ´»
    header: https://www.gmcllp.cn/logo-y.png

  - title: åšå®¢æ˜Ÿçƒ
    url: https://www.blogplanet.cn/
    desc: æ¯ä¸€ä¸ªåšå®¢éƒ½æ˜¯ä¸€ä¸ªç‹¬ç«‹æ˜Ÿçƒï¼
    tag: åšå®¢ ç¤¾åŒº
    header: https://www.blogplanet.cn/img/bkxq.png

  - title: é˜¿é”‹çš„å°å®‡å®™
    url: https://feng.pub
    desc: æ²§æµ·ä¸€ç²Ÿï¼Œå¾®äº®è€Œæ¸ºå°ã€‚
    tag: åšä¸» éšç¬”
    header: https://cravatar.cn/avatar/868740183b995d2707e307ce0a89633a?s=200

  - title: Mark's Blog
    url: https://mark.vergilisme.com/
    desc: è®°å½•ç”Ÿæ´»ï¼Œåˆ†äº«æ‰€æ€
    tag: åšä¸» æŠ€æœ¯
    header: https://mark.vergilisme.com/favicon.ico

  - title: å—å·åŸæ¢¦
    url: https://blog.southz.top/
    desc: äººç”Ÿèƒ½æœ‰å‡ å›æï¼Œå¤©æ¶¯ä½•å¤„æ— èŠ³è‰ğŸŒŸ
    tag: åšä¸» æŠ€æœ¯
    header: https://cn.cravatar.com/avatar/8418eeff381919776ab9bdb0bf488d5a?s=96&d=mp&r=g

  - title: é™¶å…¶çš„ä¸ªäººåšå®¢
    url: https://www.tqazy.com
    desc: å½“ä¸‹ï¼Œå³æ˜¯æœªæ¥
    tag: åšä¸» æŠ€æœ¯
    header: https://oss.tqazy.com/wordpress/resources/img/taoqilogo.jpg

  - title: äºŒåå…­
    url: https://www.ershiliu.com/
    desc: äººç”Ÿå¦‚é€†æ—…ï¼Œæˆ‘äº¦æ˜¯è¡Œäººã€‚
    tag: åšä¸» éšç¬”
    header: https://www.ershiliu.com/tx.jpeg

  - title: æ´—å­ã®å°çª
    url: https://xizi.live/
    desc: ä½†è¡Œå·±è·¯ æ— é—®å±±æµ·
    tag: åšä¸» éšç¬”
    header: https://cozier-1315026820.cos.ap-guangzhou.myqcloud.com/%E5%A4%B4%E5%83%8F1.png

  - title: æ—æµ·è‰åŸ
    url: https://gravatar.loli.net/
    desc: æ„¿æˆ‘ç»å†çš„è‹¦éš¾ä½ ä¸è¦ç»å†ï¼Œæ„¿æˆ‘å·²æœ‰çš„å¹¸ç¦ä½ è§¦æ‰‹å¯åŠ
    tag: åšä¸» éšç¬” ç”Ÿæ´»
    header: https://gravatar.loli.net/avatar/8391fb097fff7eec5ff0a8877b94967b

  - title: forecho's Blog
    url: https://blog.forecho.com
    desc: æŠŠç”Ÿå‘½æµªè´¹åœ¨ç¾å¥½çš„äº‹ç‰©ä¸Š
    tag: åšä¸» æŠ€æœ¯ æŠ•èµ„
    header: https://gravatar.loli.net/avatar/c7c95fe80293c0a114a2c3b0daa24003?s=150

  - title: è˜‡ SU
    url: https://suus.me/
    desc: A nook where thoughts and ideas sometimes echo
    tag: åšä¸» éšç¬” æŠ€æœ¯
    header: https://suus.me/avatar.webp

  - title: æœ±æŸçš„ç”Ÿæ´»å°è®°
    url: https://zhuxu.asia/
    desc: æ²¡æœ‰é”€å£°åŒ¿è¿¹ï¼Œæˆ‘åœ¨çƒ­çˆ±ç”Ÿæ´»
    tag: åšä¸» ç”Ÿæ´» éšç¬”
    header: https://img1.zhuxu.asia/img/logo500.png

  - title: å¢¨è¿¹æ—¥å¿—
    url: https://log.ink/
    desc: è™½å¤šå°˜è‰²æŸ“ï¼ŒçŠ¹è§å¢¨ç—•æµ“
    tag: åšä¸» éšç¬” ç”Ÿæ´»
    header: https://log.ink/wp-content/uploads/2024/12/cropped-%E5%A4%B4%E5%83%8F.png

  - title: æœè€å¸ˆè¯´
    url: https://dusays.com/
    desc: å¸ˆè€…ï¼Œä¼ é“ï¼Œæˆä¸šï¼Œè§£æƒ‘ï¼
    tag: æŠ€æœ¯ è¿ç»´ èµ„æºåˆ†äº« æ•™ç¨‹
    header: https://dusays.com/avatar.png

  - title: å–µå–µã®å°çª
    url: https://blog.meowo.moe/
    desc: ãƒ•ãƒ©ãƒ³ãƒ‰ãƒ¼ãƒ«ãƒ»ã‚¹ã‚«ãƒ¼ãƒ¬ãƒƒãƒˆèµ›é«˜ï¼
    tag: åšä¸» ACG ç”Ÿæ´»
    header: https://server.meowo.moe/api/v2/objects/avatar/o4cctz9mtnt6hmz0yv.jpg

  - title: XiaoPangçš„ä¸ªäººåšå®¢
    url: https://blog.xpdbk.com
    desc: è¿½éšæ¢¦æƒ³éœ€ç«­å°½å…¨åŠ›
    tag: åšä¸» æŠ€æœ¯ ç”Ÿæ´»
    header: https://img.xpdbk.com/file/imglol/img/avatar.jpg

  - title: Ximi's Diary
    url: https://www.ximi.me/
    desc: å¸Œç±³çš„å°çª
    tag: åšä¸» ç”Ÿæ´» éšç¬”
    header: https://www.ximi.me/tx.webp

  - title: åˆ˜éƒé˜
    url: https://vjo.cc/
    desc: ä¸€ä¸ªç§¯æå‘ä¸Šçš„ç”Ÿæ´»æ¢ç´¢è€…ï¼
    tag: åšä¸» ç”Ÿæ´» éšç¬”
    header: https://vjo.cc/usr/uploads/logo.jpeg

  - title: å›ä¸»é˜
    url: https://gfjzz.cn
    desc: å›ä¸»ï¼Œæ°¸è¿œåœ¨é«˜å³°ç­‰ä½ ï¼
    tag: åšä¸» æŠ€æœ¯ ç”Ÿæ´»
    header: https://gfjzz.cn/upload/sitelogo.png

  - title: HIPVOGUE
    url: https://hipvogue.com/
    desc: ç”Ÿæ´»ä¸­çš„æ¯ä¸ªå°äº‹ã€æ€è€ƒã€çµæ„Ÿéƒ½å€¼å¾—è¢«è®°å½•ã€‚
    tag: åšä¸» ç”Ÿæ´» éšç¬”
    header: https://hipvogue.com/hipvogue.jpg

  - title: ç›Šå‹ç½‘ç«™
    url: https://www.yiyou.bj.cn
    desc: ç¾å¥½çš„æ—¥å¸¸ç”Ÿæ´»å€¼å¾—æˆ‘ä»¬å»è®°å½•ï¼Œå¸Œæœ›æˆ‘ä»¬çš„ç”Ÿæ´»æ¯å¤©éƒ½èƒ½å……æ»¡ç€ä¹è¶£è·Ÿå¼€å¿ƒäº‹ã€‚
    tag: åšä¸» ç”Ÿæ´» éšç¬”
    header: https://www.yiyou.bj.cn/logo/youlogo.png

  - title: RhoPaperã®å°ç«™
    url: https://rhopaper.top/
    desc: çº¸è‡³æ‰§
    tag: åšä¸» éšç¬”
    header: https://rhopaper.top/avatar.jpg

  - title: å°æ—çš„å°çª
    url: https://www.xiaorin.com
    desc: åˆ†äº«æŠ€æœ¯æ•™ç¨‹ã€æ—¥å¸¸
    tag: åšä¸» æŠ€æœ¯ ç”Ÿæ´»
    header: https://www.xiaorin.com/Image.jpg


